channels:
- conda-forge
- pytorch
- defaults
- districtdatalabs
dependencies:
- python=3.6.6
- keras
- pyarrow=0.11.0
- arrow-cpp=0.11.0
- protobuf=3.6.0
- textblob=0.15.0
- xgboost=0.80
- bokeh=0.13.0
- gensim=3.4.0
- graphviz=2.40.1
- h2o=3.18.0.2
- h2o-py=3.18.0.2
- jupyterlab=0.34.9
- matplotlib=2.2.2
- nltk=3.3.0
- numpy=1.14.5
- pandas=0.23.4
- pandas-profiling=1.4.0
- pillow=5.0.0
- plotly=3.2.1
- pytorch
- torchvision
- scikit-image=0.14.0
- scikit-learn=0.20.0
- scipy=1.1.0
- scrapy=1.5.0
- seaborn=0.9.0
- spacy=2.0.12
- regex=2017.4.5
- statsmodels=0.8.0
- tensorflow=1.12.0
- tensorboard=1.12.0
- setuptools=39.1.0
- theano=1.0.1
- pygpu=0.7.5
- ipykernel=4.9.0
- theano=1.0.1
- jupyter=1.0.0
- jupyter_contrib_nbextensions=0.5.0
- jupyter_nbextensions_configurator=0.4.0
- eli5=0.8
- click=6.7
- tornado=5.1
- wordcloud
- scattertext=0.0.2.28
- requests=2.19.1
- click
- openpyxl
- autopep8
- pep8=1.7.1
- pylama=7.4.3
- black
- anaconda
- catboost=0.10.2
- lightgbm
- cython=0.28.3
- pathlib
- thinc
- hypothesis
- watermark
- pytest
- dash=0.21.1
- dash-renderer=0.13.0
- dash-html-components=0.11.0
- dash-core-components=0.23.0
- openpyxl=2.5.3
- sqlalchemy=1.2.8
- lime
- yellowbrick
- quiver_engine
- tpot
- scikit-mdr
- skrebate
- scikit-plot
- scikit-optimize
- langdetect=1.0.7
- notebook=5.6.0
- ipywidgets=7.4.1
- nbconvert=5.4.0
- pyhamcrest=1.9.0
- bz2file=0.98
- pydot
- conda-pack
- pip=18.1
- pip:
  - bayesian-optimization
  - jupyter-tensorboard
  - shap
  - msgpack
  - pixiedust


