channels:
- defaults
- conda-forge
- pytorch
dependencies:
- keras=2.1.5
- pyarrow=0.9.0
- textblob=0.15.0
- xgboost=0.7.post4
- bokeh=0.12.13
- gensim=3.4.0
- graphviz=2.40.1
- h2o=3.18.0.2
- h2o-py=3.18.0.2
- jupyterlab=0.27.0
- matplotlib=2.2.2
- nltk=3.2.5
- numpy=1.14.2
- pandas=0.22.0
- pandas-profiling=1.4.0
- pep8=1.7.1
- pillow=5.0.0
- plotly=2.4.1
- python=3.5.4
- pytorch-cpu
- torchvision-cpu
- scikit-image=0.13.1
- scikit-learn=0.19.1
- scipy=1.0.1
- scrapy=1.5.0
- seaborn=0.8.1
- spacy=2.0.11
- regex=2017.4.5
- statsmodels=0.8.0
- tensorflow=1.8.0
- tensorflow-tensorboard
- theano=1.0.1
- pygpu=0.7.5
- ipykernel=4.6.1
- theano=1.0.1
- jupyter=1.0.0
- jupyter_contrib_nbextensions=0.5.0
- jupyter_nbextensions_configurator=0.4.0
- eli5=0.8
- click=6.7
- tornado=4.5.3
- wordcloud=1.2.1
- scattertext=0.0.2.20.1
- requests
- click
- openpyxl
- autopep8
- anaconda
- catboost
- lightgbm
- cython
- pathlib
- msgpack-python
- pip:
  - watermark
  - pytest
  - sklearn
  - bayesian-optimization
  - jupyter-tensorboard
  - autopep8
  - shap
  - msgpack