channels:
- defaults
- pytorch
- conda-forge
- districtdatalabs
dependencies:
- keras=2.1.5
- pyarrow=0.9.0
- textblob=0.15.0
- xgboost=0.7.post4
- bokeh=0.12.13
- gensim=3.4.0
- graphviz=2.40.1
- h2o=3.18.0.2
- h2o-py=3.18.0.2
- jupyterlab=0.27.0
- matplotlib=2.2.2
- nltk=3.3.0
- numpy=1.14.5
- pandas=0.23.0
- pandas-profiling=1.4.0
- pillow=5.0.0
- plotly=2.7.0
- python=3.5.4
- pytorch-cpu
- torchvision-cpu
- scikit-image=0.13.1
- scikit-learn=0.19.1
- scipy=1.0.1
- scrapy=1.5.0
- seaborn=0.8.1
- spacy=2.0.11
- regex=2017.4.5
- statsmodels=0.8.0
- tensorflow=1.7.0
- tensorboard=1.7.0
- theano=1.0.1
- pygpu=0.7.5
- ipykernel=4.6.1
- theano=1.0.1
- jupyter=1.0.0
- jupyter_contrib_nbextensions=0.5.0
- jupyter_nbextensions_configurator=0.4.0
- eli5=0.8
- click=6.7
- tornado=4.5.3
- wordcloud=1.2.1
- scattertext=0.0.2.20.1
- requests=2.18.4
- click
- openpyxl
- autopep8
- pep8=1.7.1
- anaconda
- catboost=0.8.1
- lightgbm
- cython=0.28.3
- pathlib
- msgpack-numpy=0.4.3
- watermark
- pytest
- dash=0.21.1
- dash-renderer=0.13.0
- dash-html-components=0.11.0
- dash-core-components=0.23.0
- plotly
- openpyxl=2.5.3
- sqlalchemy=1.2.8
- lime
- yellowbrick
- quiver_engine
- tpot
- scikit-mdr
- skrebate
- scikit-plot
- scikit-optimize
- pip:
  - sklearn
  - bayesian-optimization
  - jupyter-tensorboard
  - shap
  - msgpack


